fieldLayouts:
  9357fcb4-586b-409c-b9ff-7694125ed353:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 277becad-d369-4f26-84d8-e2334ab7d987
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: d3505c14-1b45-45e8-a64c-c4f17f656342
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24f17415-8885-426b-a272-f0957203b94d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b23ba38-29bb-4814-a291-cc55f5281431
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 1e0bd73a-0186-4cbe-ab20-7b7172d33bb3
        userCondition: null
handle: PageNotFound
hasTitleField: false
name: 'Pagina niet gevonden'
section: b20deca7-2b9a-43db-b175-7d84070b7e4d # Pagina niet gevonden
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
