fieldLayouts:
  5c1924e1-5949-41f6-88a4-d86c0d98d6d8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: eac5a088-0fbb-44f1-a2f9-71d474e70b07
            warning: null
            width: 100
        name: Inhoud
        uid: 34cb15f8-86c5-4618-87d9-c6d9da960fa2
fs: logos
handle: logos
name: 'Logo''s'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: logos
transformSubpath: ''
