defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepagina
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2ae46a9f-5d57-42d5-b1a7-41d131d80926: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
