defaultPlacement: end
enableVersioning: true
handle: PageNotFound
name: 'Pagina niet gevonden'
propagationMethod: all
siteSettings:
  2ae46a9f-5d57-42d5-b1a7-41d131d80926: # $SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
