defaultPlacement: end
enableVersioning: true
handle: primaryNav
name: Hoofdmenu
propagationMethod: all
siteSettings:
  2ae46a9f-5d57-42d5-b1a7-41d131d80926: # $SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: ee2f93c8-fb24-48d7-8519-a167e213a6ef
type: structure
